# This is a basic workflow to help you get started with Actions

name: Docker build

on:
  push:
    branches:
      - 'main'
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN  }}
        run:
          docker login -u $DOCKER_USER -p $DOCKER_ACCESS_TOKEN
          && docker build python__simple_app
#       - name: Build image
#         run:
#           docker build python__simple_app .

      
      
      
